### PR TITLE
Upgrade registry-image to 1.0.0

### PR DESCRIPTION
**Pull request by martin-g**
v1.0.0 is the latest available version at https://github.com/concourse/registry-image-resource/releases

### CODE REVIEW

**Comment by martin-g** [comment]
I am not sure how this version is being used by Concourse but using unknown version like `1.0.99` doesn't break anything.
I was able to build the Docker image, to start a container and to execute jobs on it.

**Comment by neumayer** [comment]
I think it'd be most correct to check out that version also specifically (instead of using whatever's latest at build time):
https://github.com/neumayer/concourse-arm-worker/blob/562c0a769813a329342c587678958f7b85287b75/Dockerfile-registry-image#L3

**Comment by martin-g** [comment]
I am not sure how to do that.
I see nothing there that specifies what is the current version.

**Comment by neumayer** [comment]
This should do, just so the json file and the local build is in sync:
https://github.com/neumayer/concourse-arm-worker/pull/new/v11

**Comment by martin-g** [comment]
Closing in favor of https://github.com/neumayer/concourse-arm-worker/pull/4

**Pull request closed without merging**
