### PR TITLE
mkdir -p is needed to create deep folder structure

### PR DESCRIPTION
**Pull request by martin-g**
Add `set -ex` to print the commands and stop on first error.

It seems you (@neumayer) use a Shell alias for `mkdir` (`mkdir -p`).

### CODE REVIEW

**Comment by neumayer** [comment]
Hehe, more like I had the folder lying around by accident :-)

**Comment by martin-g** [comment]
I have an extra question to you: How do you start a worker with this image ?

I have tried with:

```
docker run \
  -it \
  --rm \
  -v /home/ubuntu/devel/concourse:/concourse \
  -e CONCOURSE_WORK_DIR=/concourse/worker \
  -e CONCOURSE_TSA_HOST=x64:2222 \
  -e CONCOURSE_TSA_PUBLIC_KEY=/concourse/keys/tsa_host_key.pub \
  -e CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse/keys/worker_key \
  concourse-arm-worker worker
```

but it gives me this error:

```
{"timestamp":"2021-01-14T12:51:48.674576601Z","level":"error","source":"worker","message":"worker.garden.load-resources.failed-to-read-resource-type-metadata","data":{"error":"open /usr/local/concourse/resource-types/registry-image/resource_metadata.json: no such file or directory","session":"1.1"}}
error: open /usr/local/concourse/resource-types/registry-image/resource_metadata.json: no such file or directory
```

I am unable to start a container with this image to explore its file system:

```
$ docker run --rm -it concourse-arm-worker /bin/bash
error: Unknown command `/bin/bash'. Please specify one command of: generate-key, land-worker, migrate, quickstart, retire-worker, web or worker
```

**Comment by martin-g** [comment]
I was able to start the image with: `docker run --rm -it --entrypoint /bin/bash concourse-arm-worker`

```
# ls -laR /usr/local/concourse/
/usr/local/concourse/:
total 16
drwxr-xr-x 1 root root 4096 Jan 14 07:55 .
drwxr-xr-x 1 root root 4096 Jan 13 13:23 ..
drwxr-xr-x 1 root root 4096 Jan 13 13:23 bin
drwxr-xr-x 3 root root 4096 Jan 14 07:55 resource-types

/usr/local/concourse/bin:
total 162744
drwxr-xr-x 1 root root     4096 Jan 13 13:23 .
drwxr-xr-x 1 root root     4096 Jan 14 07:55 ..
-rwxr-xr-x 1 root root  4101755 Jan 13 13:22 bandwidth
-rwxr-xr-x 1 root root  4581171 Jan 13 13:22 bridge
-rwxr-xr-x 1 root root 70970240 Jan 13 13:22 concourse
-rwxr-xr-x 1 root root 11585736 Jan 13 13:22 dhcp
-rwxr-xr-x 1 root root  5793740 Jan 13 13:22 firewall
-rwxr-xr-x 1 root root  3132004 Jan 13 13:22 flannel
-rwxr-xr-x 1 root root 24344096 Jan 13 13:20 gdn
-rwxr-xr-x 1 root root  4105240 Jan 13 13:22 host-device
-rwxr-xr-x 1 root root  3617995 Jan 13 13:22 host-local
-rwxr-xr-x 1 root root    87680 Jan 13 13:20 init
-rwxr-xr-x 1 root root  4237024 Jan 13 13:22 ipvlan
-rwxr-xr-x 1 root root  3340564 Jan 13 13:22 loopback
-rwxr-xr-x 1 root root  4372366 Jan 13 13:22 macvlan
-rwxr-xr-x 1 root root  3894792 Jan 13 13:22 portmap
-rwxr-xr-x 1 root root  4446889 Jan 13 13:22 ptp
-rwxr-xr-x 1 root root  3412728 Jan 13 13:22 sbr
-rwxr-xr-x 1 root root  2990275 Jan 13 13:22 static
-rwxr-xr-x 1 root root  3346836 Jan 13 13:22 tuning
-rwxr-xr-x 1 root root  4236872 Jan 13 13:22 vlan

/usr/local/concourse/resource-types:
total 12
drwxr-xr-x 3 root root 4096 Jan 14 07:55 .
drwxr-xr-x 1 root root 4096 Jan 14 07:55 ..
drwxrwxr-x 2 root root 4096 Jan 14 07:55 registry-image

/usr/local/concourse/resource-types/registry-image:
total 21212
drwxrwxr-x 2 root root     4096 Jan 14 07:55 .
drwxr-xr-x 3 root root     4096 Jan 14 07:55 ..
-rw-rw-r-- 1 root root 21708996 Jan 14 07:55 rootfs.tgz
```

**Comment by neumayer** [comment]
I think maybe the only thing was that missing metadata file. With that one the mkdir also would've worked. Sorry for being a bit messy. I pushed that file now.

This is how I start the container:

```
docker run  --restart on-failure -d -ti -v /keys/worker:/concourse-keys --privileged -e CONCOURSE_TSA_HOST=X.X.X.X:2222 -e CONCOURSE_CONTAINERD_DNS_SERVER=X.X.X.X -e CONCOURSE_CONTAINERD_ADDITIONAL_DNS_SERVER=X.X.X.X -e CONCOURSE_EPHEMERAL="true" -e CONCOURSE_RUNTIME=containerd -e CONCOURSE_WORKER_CONTAINERD_DNS_PROXY_ENABLE=false -e CONCOURSE_GARDEN_DNS_PROXY_ENABLE="" -e CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE="" -e CONCOURSE_GARDEN_USE_CONTAINERD -e CONCOURSE_TAG=aarch64 concourse-arm-worker worker
```

You should be able to avoid the proxy and dns and networking complications.

**Comment by martin-g** [comment]
Thanks for the fix! Now I am able to start the worker!

But I face a communication issue between the web node and the worker.

The web node runs on VM1 (AMD64), started as a normal (non-Docker) process:

```
#!/usr/bin/env fish

set -x CONCOURSE_POSTGRES_HOST localhost
set -x CONCOURSE_POSTGRES_USER concourse_user
set -x CONCOURSE_POSTGRES_PASSWORD concourse_pass
set -x CONCOURSE_POSTGRES_DATABASE concourse
set -x CONCOURSE_EXTERNAL_URL http://x64:8080
set -x CONCOURSE_X_FRAME_OPTIONS deny
set -x CONCOURSE_ADD_LOCAL_USER mgrigorov:password   # the password is not the real one   
set -x CONCOURSE_MAIN_TEAM_LOCAL_USER mgrigorov
set -x CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER overlay
set -x CONCOURSE_SESSION_SIGNING_KEY ./keys/session_signing_key
set -x CONCOURSE_TSA_HOST_KEY ./keys/tsa_host_key
set -x CONCOURSE_TSA_AUTHORIZED_KEYS ./keys/authorized_worker_keys
set -x CONCOURSE_BIND_IP 0.0.0.0
set -x CONCOURSE_PEER_URL http://0.0.0.0:8080
set -x CONCOURSE_AUTH_DURATION 60m

./bin/concourse web
```

The web node starts well and I can login into the UI.

Then I start the worker on a VM2 (ARM64) via Docker:

```
$ docker run  \
  -it \
  --rm \
  -v /home/ubuntu/devel/concourse:/concourse \
  -e CONCOURSE_CLUSTER_NAME=concourse-on-arm64 \
  -e CONCOURSE_WORK_DIR=/concourse/worker \
  -e CONCOURSE_TSA_PUBLIC_KEY=/concourse/keys/tsa_host_key.pub \
  -e CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse/keys/worker_key \
  -v /home/ubuntu/devel/concourse/keys:/concourse-keys \
  --privileged \
  -e CONCOURSE_TSA_HOST=192.168.0.206:2222 \    # this is VM1
  -e CONCOURSE_EPHEMERAL="true" \
  -e CONCOURSE_TAG=aarch64 \
  concourse-arm-worker worker
```

After starting the worker node the web node logs the following:
```
{"timestamp":"2021-01-15T09:19:48.463716938Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.forwarded-tcpip","data":{"bind-addr":"0.0.0.0:7777","bound-port":37925,"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1"}}
{"timestamp":"2021-01-15T09:19:48.463758029Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.forwarded-tcpip","data":{"bind-addr":"0.0.0.0:7788","bound-port":35727,"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1"}}
{"timestamp":"2021-01-15T09:19:48.463781322Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.start","data":{"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1"}}
{"timestamp":"2021-01-15T09:19:48.463796760Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.register.start","data":{"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1.2","worker-address":"127.0.0.1:37925","worker-platform":"linux","worker-tags":"aarch64"}}
```

So, it seems it is registered!


But the worker node logs some errors:
```
{"timestamp":"2021-01-15T09:19:48.333158575Z","level":"info","source":"worker","message":"worker.garden.forwarding-garden-env-var","data":{"env":"CONCOURSE_GARDEN_USE_CONTAINERD","flag":"use-containerd","ses
sion":"1"}}          
{"timestamp":"2021-01-15T09:19:48.424334910Z","level":"info","source":"baggageclaim","message":"baggageclaim.using-driver","data":{"driver":"btrfs"}}                                                          
{"timestamp":"2021-01-15T09:19:48.425637381Z","level":"info","source":"baggageclaim","message":"baggageclaim.listening","data":{"addr":"127.0.0.1:7788"}}                                                      
{"timestamp":"2021-01-15T09:19:48.425314368Z","level":"info","source":"worker","message":"worker.garden.dns-proxy.started","data":{"session":"1.2"}}
{"timestamp":"2021-01-15T09:19:48.425637381Z","level":"info","source":"baggageclaim","message":"baggageclaim.listening","data":{"addr":"127.0.0.1:7788"}}                                            [104/1258]
{"timestamp":"2021-01-15T09:19:48.425314368Z","level":"info","source":"worker","message":"worker.garden.dns-proxy.started","data":{"session":"1.2"}}                                                           unknown flag `use-containerd'                                                                                                                                                                                  
unknown flag `use-containerd'                                                                                                                                                                                  {"timestamp":"2021-01-15T09:19:48.434035545Z","level":"error","source":"worker","message":"worker.garden.gdn-runner.logging-runner-exited","data":{"error":"exit status 1","session":"1.4"}}                   
{"timestamp":"2021-01-15T09:19:48.434176076Z","level":"info","source":"worker","message":"worker.garden.dns-proxy-runner.logging-runner-exited","data":{"session":"1.3"}}                                      {"timestamp":"2021-01-15T09:19:48.434265017Z","level":"error","source":"worker","message":"worker.garden-runner.logging-runner-exited","data":{"error":"Exit trace for group:\ngdn exited with error: exit stat
us 1\ndns-proxy exited with nil\n","session":"8"}}                                                                                                                                                             {"timestamp":"2021-01-15T09:19:48.434331647Z","level":"info","source":"worker","message":"worker.container-sweeper.sweep-cancelled-by-signal","data":{"session":"6","signal":2}}                               
{"timestamp":"2021-01-15T09:19:48.434379478Z","level":"info","source":"worker","message":"worker.container-sweeper.logging-runner-exited","data":{"session":"13"}}                                             {"timestamp":"2021-01-15T09:19:48.434404188Z","level":"info","source":"worker","message":"worker.volume-sweeper.sweep-cancelled-by-signal","data":{"session":"7","signal":2}}                                  
{"timestamp":"2021-01-15T09:19:48.434431998Z","level":"info","source":"worker","message":"worker.volume-sweeper.logging-runner-exited","data":{"session":"14"}}                                                {"timestamp":"2021-01-15T09:19:48.434442578Z","level":"info","source":"worker","message":"worker.baggageclaim-runner.logging-runner-exited","data":{"session":"9"}}                                            
{"timestamp":"2021-01-15T09:19:48.434429858Z","level":"info","source":"worker","message":"worker.healthcheck-runner.logging-runner-exited","data":{"session":"11"}}                                            {"timestamp":"2021-01-15T09:19:48.434482088Z","level":"info","source":"worker","message":"worker.debug-runner.logging-runner-exited","data":{"session":"10"}}                                                  
{"timestamp":"2021-01-15T09:19:48.464746572Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}                                                                                                                                        
{"timestamp":"2021-01-15T09:19:49.464890166Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}                                                                                                                                                                                                              
{"timestamp":"2021-01-15T09:19:49.465125558Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}               
```

Executing a simply task fails with:
```
$ fly -t tutorial execute -c task_hello_world.yml
executing build 2 at http://127.0.0.1:8080/builds/2 
initializing
no workers
errored
```

In the web node logs I see:
```
{"timestamp":"2021-01-15T09:20:20.952695586Z","level":"error","source":"tsa","message":"tsa.connection.request.failed-to-accept","data":{"addr":"[::]:35727","error":"accept tcp [::]:35727: use of closed network connection","remote":"192.168.0.232:46850","requested-addr":"0.0.0.0:7788","session":"6.3","type":"tcpip-forward"}}
{"timestamp":"2021-01-15T09:20:20.952771128Z","level":"error","source":"tsa","message":"tsa.connection.request.failed-to-accept","data":{"addr":"[::]:37925","error":"accept tcp [::]:37925: use of closed network connection","remote":"192.168.0.232:46850","requested-addr":"0.0.0.0:7777","session":"6.1","type":"tcpip-forward"}}
{"timestamp":"2021-01-15T09:20:20.952772304Z","level":"error","source":"tsa","message":"tsa.connection.channel.command.register.failed-to-fetch-containers","data":{"command":"forward-worker","error":"Get \"http://127.0.0.1:37925/containers\": EOF","remote":"192.168.0.232:46850","session":"6.4.1.2"}}
{"timestamp":"2021-01-15T09:20:20.952989611Z","level":"error","source":"tsa","message":"tsa.connection.channel.command.register.failed-to-list-volumes","data":{"command":"forward-worker","error":"Get \"http://127.0.0.1:35727/volumes\": dial tcp 127.0.0.1:35727: connect: connection refused","remote":"192.168.0.232:46850","session":"6.4.1.2"}}
{"timestamp":"2021-01-15T09:20:20.953010077Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.register.failed-to-reach-worker","data":{"baggageclaim-took":"178.218µs","command":"forward-worker","garden-took":"32.489000263s","remote":"192.168.0.232:46850","session":"6.4.1.2"}}
{"timestamp":"2021-01-15T09:20:20.953023050Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.register.done","data":{"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1.2","worker-address":"127.0.0.1:37925","worker-platform":"linux","worker-tags":"aarch64"}}
{"timestamp":"2021-01-15T09:20:20.953048825Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.done","data":{"command":"forward-worker","remote":"192.168.0.232:46850","session":"6.4.1"}}
```

It seems the web node is trying to send commands to the worker node at port 46850 but since this is a random port for the client socket it is not exposed by Docker and thus the connection fails. At least this is what I think happens.

Any idea how to overcome this issue ?

Thank you for your help, @neumayer !

**Comment by martin-g** [comment]
I've found a solution!
In your start command you use `CONCOURCE_RUNTIME=containerd` but I was not able to start it with `containerd` because of those two lines: https://github.com/neumayer/concourse-arm-worker/blob/3c1f881e0987ca0bb56c5ab42caf08964bf50673/Dockerfile#L34-L35
When trying to start the worker node it failed with: `error: cannot use CONCOURSE_GARDEN_ environment variables with Containerd`
So, I've commented out those lines and now the worker node properly connects!

```
$  fly -t tutorial workers -d
name          containers  platform  tags     team  state    version  age  garden address   baggageclaim url        active tasks  resource types
arm64-worker  0           linux     aarch64  none  running  2.2      6s   127.0.0.1:46457  http://127.0.0.1:40443  0             registry-image
```

But trying to execute a task fails with:
```
$ fly -t tutorial execute -c task_hello_world.yml
executing build 8 at http://127.0.0.1:8080/builds/8 
initializing
no workers satisfying: platform 'linux'
errored
``` 

```
$ cat task_hello_world.yml
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: echo
  args: [hello world]
```

**Comment by martin-g** [comment]
Removing `-e CONCOURSE_TAGS=aarch64` in the worker and changing `type: docker-image` with `type: registry-image` worked around the last issue.

Now the problem is that it cannot use `busybox` ...

**Pull request merged**
